In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics
import pickle


data=pd.read_csv('ANN.csv')
data.head()

x= data.drop(columns=['UTS',' Yield'])
y=data[[' Yield']]


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=42, shuffle=True)




In [2]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=1 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=1:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_1','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=1: 6.81231754445615 %
coefficient of determination (R^2) = 0.7875512499424696
[[130.]
 [170.]
 [110.]
 [120.]
 [160.]
 [100.]
 [120.]
 [160.]
 [170.]
 [270.]
 [ 65.]
 [ 83.]
 [120.]
 [ 83.]
 [180.]
 [220.]
 [ 83.]
 [120.]
 [170.]
 [130.]
 [120.]
 [ 50.]
 [110.]
 [110.]
 [110.]
 [150.]
 [250.]
 [130.]
 [ 83.]
 [ 74.]
 [120.]
 [140.]
 [200.]
 [120.]
 [220.]
 [160.]
 [250.]
 [250.]
 [130.]]


In [3]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=2 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=2:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_2','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=2: 12.611116109241141 %
coefficient of determination (R^2) = 0.6962473679870518
[[120. ]
 [150. ]
 [110. ]
 [115. ]
 [160. ]
 [ 91.5]
 [115. ]
 [160. ]
 [160. ]
 [260. ]
 [ 57.5]
 [ 78.5]
 [101.5]
 [ 66.5]
 [200. ]
 [200. ]
 [ 91.5]
 [115. ]
 [160. ]
 [140. ]
 [125. ]
 [ 57.5]
 [110. ]
 [105. ]
 [115. ]
 [160. ]
 [260. ]
 [140. ]
 [101.5]
 [ 78.5]
 [130. ]
 [130. ]
 [190. ]
 [101.5]
 [200. ]
 [160. ]
 [260. ]
 [260. ]
 [125. ]]


In [4]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=3 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=3:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_3','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=3: 13.54164233402812 %
coefficient of determination (R^2) = 0.722361866463137
[[116.66666667]
 [136.66666667]
 [113.33333333]
 [113.33333333]
 [156.66666667]
 [ 82.66666667]
 [120.        ]
 [156.66666667]
 [160.        ]
 [230.        ]
 [ 71.66666667]
 [ 92.33333333]
 [ 95.33333333]
 [ 66.        ]
 [200.        ]
 [200.        ]
 [ 77.66666667]
 [120.        ]
 [160.        ]
 [150.        ]
 [130.        ]
 [ 66.        ]
 [113.33333333]
 [110.        ]
 [110.        ]
 [150.        ]
 [230.        ]
 [150.        ]
 [ 95.33333333]
 [ 92.33333333]
 [130.        ]
 [130.        ]
 [200.        ]
 [134.33333333]
 [200.        ]
 [156.66666667]
 [230.        ]
 [230.        ]
 [130.        ]]


In [5]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=4 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=4:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_4','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=4: 14.935371631883115 %
coefficient of determination (R^2) = 0.6534152225752881
[[130.  ]
 [130.  ]
 [112.5 ]
 [125.  ]
 [147.5 ]
 [ 89.5 ]
 [130.  ]
 [160.  ]
 [160.  ]
 [210.  ]
 [ 74.5 ]
 [ 90.  ]
 [ 90.  ]
 [ 74.5 ]
 [180.  ]
 [180.  ]
 [ 74.5 ]
 [130.  ]
 [160.  ]
 [152.5 ]
 [116.  ]
 [ 74.5 ]
 [125.  ]
 [103.25]
 [103.25]
 [152.5 ]
 [210.  ]
 [152.5 ]
 [ 90.  ]
 [ 90.  ]
 [127.5 ]
 [116.  ]
 [180.  ]
 [121.5 ]
 [180.  ]
 [160.  ]
 [210.  ]
 [210.  ]
 [116.  ]]


In [6]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=5 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=5:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_5','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=5: 17.576871508243553 %
coefficient of determination (R^2) = 0.5476895528742156
[[128. ]
 [136. ]
 [110. ]
 [122. ]
 [152. ]
 [ 81.6]
 [136. ]
 [152. ]
 [154. ]
 [194. ]
 [ 81.6]
 [100. ]
 [112. ]
 [ 76.2]
 [166. ]
 [166. ]
 [ 81.6]
 [124. ]
 [154. ]
 [154. ]
 [118.6]
 [ 76.2]
 [126. ]
 [104.6]
 [104.6]
 [154. ]
 [200. ]
 [154. ]
 [100. ]
 [100. ]
 [118.6]
 [118.6]
 [160.6]
 [112. ]
 [166. ]
 [152. ]
 [194. ]
 [200. ]
 [118.6]]


In [7]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=6 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=6:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_6','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=6: 19.951427953495124 %
coefficient of determination (R^2) = 0.4402096189765735
[[133.33333333]
 [140.        ]
 [105.5       ]
 [128.33333333]
 [148.33333333]
 [ 86.33333333]
 [131.66666667]
 [148.33333333]
 [170.        ]
 [188.33333333]
 [ 81.83333333]
 [103.33333333]
 [116.66666667]
 [ 77.33333333]
 [149.16666667]
 [156.66666667]
 [ 86.33333333]
 [121.66666667]
 [148.33333333]
 [148.33333333]
 [111.16666667]
 [ 81.83333333]
 [131.66666667]
 [ 98.        ]
 [ 98.        ]
 [148.33333333]
 [193.33333333]
 [148.33333333]
 [103.33333333]
 [103.33333333]
 [112.66666667]
 [111.16666667]
 [147.66666667]
 [101.66666667]
 [156.66666667]
 [145.        ]
 [188.33333333]
 [193.33333333]
 [111.16666667]]


In [8]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=7 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=7:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_7','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=7: 21.648348600539805 %
coefficient of determination (R^2) = 0.3342305196014862
[[130.        ]
 [144.28571429]
 [113.28571429]
 [131.42857143]
 [142.85714286]
 [ 91.14285714]
 [134.28571429]
 [142.85714286]
 [162.85714286]
 [184.28571429]
 [ 85.85714286]
 [107.14285714]
 [117.14285714]
 [ 76.85714286]
 [135.        ]
 [143.57142857]
 [ 89.71428571]
 [127.14285714]
 [142.85714286]
 [142.85714286]
 [107.14285714]
 [ 82.        ]
 [128.57142857]
 [ 91.14285714]
 [102.57142857]
 [142.85714286]
 [184.28571429]
 [142.85714286]
 [107.14285714]
 [107.14285714]
 [107.14285714]
 [107.14285714]
 [137.14285714]
 [ 96.42857143]
 [143.57142857]
 [142.85714286]
 [184.28571429]
 [184.28571429]
 [107.14285714]]


In [9]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=8 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=8:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_8','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=8: 22.38809324967533 %
coefficient of determination (R^2) = 0.2535445766929739
[[133.75 ]
 [145.   ]
 [115.375]
 [127.5  ]
 [138.75 ]
 [ 93.5  ]
 [130.   ]
 [138.75 ]
 [156.25 ]
 [176.25 ]
 [ 85.5  ]
 [118.75 ]
 [118.75 ]
 [ 82.25 ]
 [128.5  ]
 [131.875]
 [ 93.5  ]
 [121.625]
 [138.75 ]
 [137.5  ]
 [118.75 ]
 [ 85.5  ]
 [125.   ]
 [ 93.5  ]
 [ 96.   ]
 [138.75 ]
 [176.25 ]
 [138.75 ]
 [100.   ]
 [118.75 ]
 [118.75 ]
 [118.75 ]
 [137.5  ]
 [ 98.125]
 [131.875]
 [138.75 ]
 [176.25 ]
 [176.25 ]
 [118.75 ]]


In [10]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=9 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=9:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_9','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=9: 21.684052654908374 %
coefficient of determination (R^2) = 0.2429826837945135
[[126.11111111]
 [142.22222222]
 [120.33333333]
 [127.77777778]
 [135.55555556]
 [ 92.33333333]
 [127.77777778]
 [135.55555556]
 [151.11111111]
 [168.88888889]
 [ 88.22222222]
 [111.11111111]
 [125.55555556]
 [ 95.33333333]
 [122.44444444]
 [126.44444444]
 [ 92.33333333]
 [124.77777778]
 [151.11111111]
 [134.44444444]
 [125.55555556]
 [ 84.22222222]
 [120.33333333]
 [ 97.55555556]
 [ 97.55555556]
 [135.55555556]
 [168.88888889]
 [134.44444444]
 [ 96.11111111]
 [111.11111111]
 [130.        ]
 [125.55555556]
 [135.55555556]
 [107.22222222]
 [126.44444444]
 [135.55555556]
 [168.88888889]
 [168.88888889]
 [125.55555556]]


In [11]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=10 ,metric='chebyshev')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=10:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('chebyshev_saved_10','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=10: 21.940491961420264 %
coefficient of determination (R^2) = 0.19882337035730158
[[121.8]
 [141. ]
 [116.6]
 [123.3]
 [132. ]
 [ 96.1]
 [123.3]
 [135. ]
 [153. ]
 [163. ]
 [ 86.8]
 [106.5]
 [135. ]
 [ 97.8]
 [118.5]
 [123.8]
 [ 96.1]
 [123.3]
 [147. ]
 [129.3]
 [135. ]
 [ 87.8]
 [116.6]
 [103.8]
 [103.8]
 [139. ]
 [163. ]
 [132. ]
 [106.5]
 [106.5]
 [135. ]
 [135. ]
 [135. ]
 [107.5]
 [122.1]
 [135. ]
 [163. ]
 [163. ]
 [135. ]]
