In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics
import pickle


data=pd.read_csv('ANN.csv')
data.head()

x= data.drop(columns=['UTS',' Yield'])
y=data[[' Yield']]


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=42, shuffle=True)




In [2]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=1 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=1:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)


print(y_pred)

with open('euclidean_saved_1','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=1: 7.9421124977805135 %
coefficient of determination (R^2) = 0.6898762426552936
[[130.]
 [170.]
 [110.]
 [120.]
 [160.]
 [100.]
 [120.]
 [160.]
 [170.]
 [270.]
 [ 65.]
 [ 83.]
 [120.]
 [ 50.]
 [180.]
 [220.]
 [ 83.]
 [120.]
 [170.]
 [130.]
 [120.]
 [ 50.]
 [110.]
 [110.]
 [110.]
 [150.]
 [250.]
 [130.]
 [ 83.]
 [ 74.]
 [120.]
 [140.]
 [200.]
 [ 83.]
 [220.]
 [160.]
 [250.]
 [250.]
 [130.]]


In [3]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=2 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=2:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_2','wb') as f:
    pickle.dump(model,f)
    


Mean Absolute Percentage Error for k=2: 11.766520168315608 %
coefficient of determination (R^2) = 0.7147039992214228
[[120. ]
 [150. ]
 [110. ]
 [115. ]
 [160. ]
 [ 91.5]
 [115. ]
 [160. ]
 [160. ]
 [260. ]
 [ 57.5]
 [ 78.5]
 [101.5]
 [ 57.5]
 [200. ]
 [200. ]
 [ 91.5]
 [115. ]
 [160. ]
 [140. ]
 [130. ]
 [ 57.5]
 [110. ]
 [105. ]
 [115. ]
 [160. ]
 [260. ]
 [140. ]
 [ 83. ]
 [ 78.5]
 [125. ]
 [130. ]
 [190. ]
 [141.5]
 [200. ]
 [160. ]
 [260. ]
 [260. ]
 [135. ]]


In [4]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=3 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=3:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_3','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=3: 13.014068527955702 %
coefficient of determination (R^2) = 0.7233881437644785
[[116.66666667]
 [136.66666667]
 [113.33333333]
 [113.33333333]
 [156.66666667]
 [ 97.66666667]
 [120.        ]
 [156.66666667]
 [160.        ]
 [230.        ]
 [ 66.        ]
 [ 92.33333333]
 [ 92.33333333]
 [ 66.        ]
 [200.        ]
 [200.        ]
 [ 82.66666667]
 [120.        ]
 [160.        ]
 [150.        ]
 [130.        ]
 [ 66.        ]
 [113.33333333]
 [110.        ]
 [110.        ]
 [160.        ]
 [230.        ]
 [150.        ]
 [ 95.33333333]
 [ 92.33333333]
 [130.        ]
 [130.        ]
 [200.        ]
 [134.33333333]
 [200.        ]
 [156.66666667]
 [230.        ]
 [230.        ]
 [130.        ]]


In [5]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=4 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=4:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_4','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=4: 14.90498600120575 %
coefficient of determination (R^2) = 0.6197710765987681
[[130.  ]
 [142.5 ]
 [112.5 ]
 [125.  ]
 [147.5 ]
 [ 89.5 ]
 [115.  ]
 [160.  ]
 [160.  ]
 [210.  ]
 [ 74.5 ]
 [ 90.  ]
 [ 90.  ]
 [ 70.25]
 [180.  ]
 [180.  ]
 [ 74.5 ]
 [115.  ]
 [160.  ]
 [142.5 ]
 [118.25]
 [ 74.5 ]
 [117.5 ]
 [103.25]
 [103.25]
 [160.  ]
 [210.  ]
 [142.5 ]
 [ 90.  ]
 [ 90.  ]
 [118.25]
 [118.25]
 [180.  ]
 [117.  ]
 [180.  ]
 [160.  ]
 [210.  ]
 [210.  ]
 [118.25]]


In [6]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=5 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=5:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_5','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=5: 18.206582099311614 %
coefficient of determination (R^2) = 0.5020380793305002
[[128. ]
 [146. ]
 [122. ]
 [122. ]
 [152. ]
 [ 81.6]
 [124. ]
 [152. ]
 [154. ]
 [194. ]
 [ 81.6]
 [100. ]
 [112. ]
 [ 76.2]
 [160.6]
 [160.6]
 [ 81.6]
 [108.6]
 [154. ]
 [146. ]
 [118.6]
 [ 81.6]
 [116. ]
 [104.6]
 [104.6]
 [154. ]
 [194. ]
 [146. ]
 [100. ]
 [100. ]
 [118.6]
 [118.6]
 [160.6]
 [110.2]
 [160.6]
 [152. ]
 [194. ]
 [194. ]
 [118.6]]


In [7]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=6 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=6:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_6','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=6: 20.518569799138305 %
coefficient of determination (R^2) = 0.40489108548241104
[[133.33333333]
 [140.        ]
 [118.33333333]
 [128.33333333]
 [148.33333333]
 [ 88.        ]
 [128.33333333]
 [145.        ]
 [148.33333333]
 [188.33333333]
 [ 81.83333333]
 [105.        ]
 [116.66666667]
 [ 77.33333333]
 [147.66666667]
 [147.66666667]
 [ 88.        ]
 [108.83333333]
 [148.33333333]
 [148.33333333]
 [112.66666667]
 [ 81.83333333]
 [123.33333333]
 [ 98.        ]
 [ 98.        ]
 [148.33333333]
 [188.33333333]
 [148.33333333]
 [103.33333333]
 [105.        ]
 [112.66666667]
 [112.66666667]
 [147.66666667]
 [121.83333333]
 [147.66666667]
 [145.        ]
 [188.33333333]
 [188.33333333]
 [112.66666667]]


In [8]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=7 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=7:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_7','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=7: 22.275632814505585 %
coefficient of determination (R^2) = 0.3143903314436246
[[137.14285714]
 [144.28571429]
 [124.28571429]
 [124.28571429]
 [142.85714286]
 [ 91.14285714]
 [125.71428571]
 [142.85714286]
 [162.85714286]
 [184.28571429]
 [ 85.85714286]
 [107.14285714]
 [118.57142857]
 [ 76.85714286]
 [137.14285714]
 [137.14285714]
 [ 91.14285714]
 [116.14285714]
 [142.85714286]
 [142.85714286]
 [107.14285714]
 [ 85.85714286]
 [128.57142857]
 [ 91.14285714]
 [102.57142857]
 [142.85714286]
 [184.28571429]
 [142.85714286]
 [107.14285714]
 [107.14285714]
 [107.14285714]
 [107.14285714]
 [137.14285714]
 [115.        ]
 [137.14285714]
 [140.        ]
 [184.28571429]
 [184.28571429]
 [107.14285714]]


In [9]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=8 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=8:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_8','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=8: 23.18281520302046 %
coefficient of determination (R^2) = 0.2367306837996006
[[133.75 ]
 [145.   ]
 [119.125]
 [125.   ]
 [138.75 ]
 [ 93.5  ]
 [130.   ]
 [138.75 ]
 [156.25 ]
 [176.25 ]
 [ 90.125]
 [118.75 ]
 [118.75 ]
 [ 82.25 ]
 [128.125]
 [128.125]
 [ 93.5  ]
 [120.375]
 [138.75 ]
 [138.75 ]
 [118.75 ]
 [ 85.5  ]
 [125.   ]
 [ 93.5  ]
 [ 96.   ]
 [138.75 ]
 [176.25 ]
 [138.75 ]
 [118.75 ]
 [118.75 ]
 [118.75 ]
 [118.75 ]
 [137.5  ]
 [106.875]
 [128.125]
 [138.75 ]
 [176.25 ]
 [176.25 ]
 [118.75 ]]


In [10]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=9 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=9:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_9','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=9: 22.612552881277672 %
coefficient of determination (R^2) = 0.19963989559877282
[[126.11111111]
 [142.22222222]
 [120.33333333]
 [120.33333333]
 [135.55555556]
 [ 92.33333333]
 [124.77777778]
 [135.55555556]
 [151.11111111]
 [168.88888889]
 [ 92.33333333]
 [111.11111111]
 [125.55555556]
 [ 85.33333333]
 [119.44444444]
 [119.44444444]
 [ 92.33333333]
 [124.77777778]
 [135.55555556]
 [134.44444444]
 [125.55555556]
 [ 84.22222222]
 [120.33333333]
 [100.88888889]
 [ 97.55555556]
 [135.55555556]
 [175.55555556]
 [134.44444444]
 [112.77777778]
 [111.11111111]
 [125.55555556]
 [125.55555556]
 [135.55555556]
 [107.22222222]
 [119.44444444]
 [135.55555556]
 [175.55555556]
 [175.55555556]
 [125.55555556]]


In [11]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=10 ,metric='euclidean')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=10:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('euclidean_saved_10','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=10: 22.31454402084367 %
coefficient of determination (R^2) = 0.18716005083764164
[[121.8]
 [139. ]
 [114.8]
 [123.3]
 [132. ]
 [ 96.1]
 [123.3]
 [139. ]
 [147. ]
 [163. ]
 [ 91.4]
 [106.5]
 [135. ]
 [ 90.8]
 [121.5]
 [121.5]
 [ 91.4]
 [123.3]
 [147. ]
 [132. ]
 [119.5]
 [ 87.8]
 [114.8]
 [103.8]
 [103.8]
 [132. ]
 [169. ]
 [132. ]
 [106.5]
 [106.5]
 [119.5]
 [119.5]
 [135. ]
 [109.5]
 [121.5]
 [132. ]
 [169. ]
 [169. ]
 [119.5]]
