In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics
import pickle


data=pd.read_csv('ANN.csv')
data.head()

x= data.drop(columns=['UTS',' Yield'])
y=data[[' Yield']]


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=42, shuffle=True)




In [2]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=1 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=1:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_1','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=1: 7.534872678775987 %
coefficient of determination (R^2) = 0.726981153061381
[[130.]
 [170.]
 [110.]
 [120.]
 [160.]
 [100.]
 [120.]
 [160.]
 [170.]
 [270.]
 [ 65.]
 [ 83.]
 [120.]
 [ 50.]
 [180.]
 [220.]
 [ 83.]
 [120.]
 [170.]
 [130.]
 [120.]
 [ 50.]
 [110.]
 [110.]
 [110.]
 [150.]
 [250.]
 [130.]
 [ 83.]
 [ 74.]
 [120.]
 [140.]
 [200.]
 [110.]
 [220.]
 [160.]
 [250.]
 [250.]
 [130.]]


In [3]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=2 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=2:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_2','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=2: 12.046752888414963 %
coefficient of determination (R^2) = 0.7119040696002025
[[120. ]
 [150. ]
 [110. ]
 [115. ]
 [160. ]
 [ 91.5]
 [115. ]
 [160. ]
 [160. ]
 [260. ]
 [ 57.5]
 [ 78.5]
 [ 97. ]
 [ 57.5]
 [200. ]
 [200. ]
 [ 91.5]
 [115. ]
 [160. ]
 [150. ]
 [130. ]
 [ 57.5]
 [110. ]
 [105. ]
 [105. ]
 [155. ]
 [260. ]
 [150. ]
 [ 83. ]
 [ 78.5]
 [130. ]
 [130. ]
 [190. ]
 [155. ]
 [200. ]
 [160. ]
 [260. ]
 [260. ]
 [135. ]]


In [4]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=3 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=3:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_3','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=3: 12.895509142222036 %
coefficient of determination (R^2) = 0.7183575152519317
[[116.66666667]
 [153.33333333]
 [113.33333333]
 [113.33333333]
 [156.66666667]
 [ 97.66666667]
 [120.        ]
 [156.66666667]
 [160.        ]
 [216.66666667]
 [ 71.66666667]
 [ 92.33333333]
 [ 92.33333333]
 [ 66.        ]
 [200.        ]
 [200.        ]
 [ 82.66666667]
 [120.        ]
 [160.        ]
 [150.        ]
 [130.        ]
 [ 66.        ]
 [116.66666667]
 [110.        ]
 [110.        ]
 [156.66666667]
 [230.        ]
 [150.        ]
 [ 80.        ]
 [ 92.33333333]
 [130.        ]
 [130.        ]
 [200.        ]
 [131.        ]
 [200.        ]
 [156.66666667]
 [230.        ]
 [230.        ]
 [130.        ]]


In [5]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=4 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=4:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_4','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=4: 15.14058823529969 %
coefficient of determination (R^2) = 0.6071976864654127
[[130.  ]
 [155.  ]
 [112.5 ]
 [112.5 ]
 [160.  ]
 [ 89.5 ]
 [115.  ]
 [160.  ]
 [160.  ]
 [205.  ]
 [ 74.5 ]
 [ 90.  ]
 [ 90.  ]
 [ 68.  ]
 [180.  ]
 [180.  ]
 [ 74.5 ]
 [115.  ]
 [160.  ]
 [142.5 ]
 [118.25]
 [ 74.5 ]
 [117.5 ]
 [103.25]
 [103.25]
 [160.  ]
 [210.  ]
 [142.5 ]
 [ 90.  ]
 [ 90.  ]
 [118.25]
 [118.25]
 [180.  ]
 [114.5 ]
 [180.  ]
 [160.  ]
 [210.  ]
 [210.  ]
 [118.25]]


In [6]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=5 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=5:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_5','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=5: 19.511347052391635 %
coefficient of determination (R^2) = 0.46579100378933147
[[128. ]
 [146. ]
 [122. ]
 [110. ]
 [152. ]
 [ 81.6]
 [108.6]
 [150. ]
 [154. ]
 [194. ]
 [ 81.6]
 [100. ]
 [100. ]
 [ 71. ]
 [160.6]
 [160.6]
 [ 81.6]
 [108.6]
 [154. ]
 [146. ]
 [109.4]
 [ 81.6]
 [116. ]
 [104.6]
 [ 95.6]
 [154. ]
 [194. ]
 [146. ]
 [100. ]
 [100. ]
 [109.4]
 [109.4]
 [160.6]
 [127.6]
 [160.6]
 [150. ]
 [194. ]
 [200. ]
 [109.4]]


In [7]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=6 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=6:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_6','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=6: 21.341225558269763 %
coefficient of determination (R^2) = 0.3668045636899191
[[125.        ]
 [150.        ]
 [128.33333333]
 [118.33333333]
 [145.        ]
 [ 88.        ]
 [108.83333333]
 [145.        ]
 [148.33333333]
 [188.33333333]
 [ 81.83333333]
 [103.33333333]
 [103.33333333]
 [ 73.        ]
 [146.16666667]
 [146.16666667]
 [ 88.        ]
 [108.83333333]
 [146.66666667]
 [140.        ]
 [105.        ]
 [ 81.83333333]
 [123.33333333]
 [ 98.        ]
 [101.33333333]
 [148.33333333]
 [188.33333333]
 [148.33333333]
 [103.33333333]
 [103.33333333]
 [105.        ]
 [105.        ]
 [146.16666667]
 [123.        ]
 [146.16666667]
 [145.        ]
 [188.33333333]
 [193.33333333]
 [105.        ]]


In [8]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=7 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=7:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_7','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=7: 23.16947223021529 %
coefficient of determination (R^2) = 0.2794764463361705
[[130.        ]
 [144.28571429]
 [128.57142857]
 [113.28571429]
 [142.85714286]
 [ 91.14285714]
 [116.14285714]
 [140.        ]
 [142.85714286]
 [178.57142857]
 [ 85.85714286]
 [107.14285714]
 [107.14285714]
 [ 76.85714286]
 [137.14285714]
 [137.14285714]
 [ 91.14285714]
 [109.        ]
 [142.85714286]
 [142.85714286]
 [107.14285714]
 [ 85.85714286]
 [128.57142857]
 [ 91.14285714]
 [102.57142857]
 [142.85714286]
 [184.28571429]
 [142.85714286]
 [107.14285714]
 [107.14285714]
 [107.14285714]
 [107.14285714]
 [137.14285714]
 [116.        ]
 [137.14285714]
 [140.        ]
 [184.28571429]
 [184.28571429]
 [107.14285714]]


In [9]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=8 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=8:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_8','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=8: 22.585181339627862 %
coefficient of determination (R^2) = 0.2708757145148082
[[121.875]
 [145.   ]
 [125.   ]
 [115.375]
 [138.75 ]
 [ 93.5  ]
 [121.625]
 [138.75 ]
 [156.25 ]
 [176.25 ]
 [ 88.875]
 [118.75 ]
 [118.75 ]
 [ 82.25 ]
 [128.125]
 [137.5  ]
 [ 90.125]
 [115.375]
 [138.75 ]
 [137.5  ]
 [118.75 ]
 [ 85.5  ]
 [120.625]
 [ 93.5  ]
 [ 96.   ]
 [138.75 ]
 [176.25 ]
 [137.5  ]
 [101.875]
 [118.75 ]
 [118.75 ]
 [118.75 ]
 [135.   ]
 [111.875]
 [137.5  ]
 [138.75 ]
 [176.25 ]
 [175.   ]
 [118.75 ]]


In [10]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=9 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=9:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_9','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=9: 21.580352357148648 %
coefficient of determination (R^2) = 0.2696139565189968
[[126.11111111]
 [142.22222222]
 [118.33333333]
 [120.33333333]
 [135.55555556]
 [ 92.33333333]
 [124.77777778]
 [135.55555556]
 [151.11111111]
 [168.88888889]
 [ 92.33333333]
 [111.11111111]
 [125.55555556]
 [ 85.33333333]
 [127.22222222]
 [136.66666667]
 [ 92.33333333]
 [119.22222222]
 [151.11111111]
 [134.44444444]
 [125.55555556]
 [ 84.22222222]
 [118.33333333]
 [ 97.55555556]
 [ 97.55555556]
 [135.55555556]
 [168.88888889]
 [134.44444444]
 [ 96.11111111]
 [111.11111111]
 [125.55555556]
 [125.55555556]
 [135.55555556]
 [112.77777778]
 [136.66666667]
 [135.55555556]
 [168.88888889]
 [168.88888889]
 [125.55555556]]


In [11]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=10 ,metric='manhattan')
model.fit(x_train, y_train)

y_pred = model.predict(x)
y_predi = model.predict(x)

mape= 100* (metrics.mean_absolute_percentage_error(y, y_pred))
print('Mean Absolute Percentage Error for k=10:', mape , '%')

f=model.score(x,y)
print('coefficient of determination (R^2) =',f)

print(y_pred)

with open('manhattan_saved_10','wb') as f:
    pickle.dump(model,f)

Mean Absolute Percentage Error for k=10: 22.090152834113603 %
coefficient of determination (R^2) = 0.22247281931255058
[[118.5]
 [139. ]
 [114.8]
 [123.3]
 [132. ]
 [ 96.1]
 [123.3]
 [139. ]
 [153. ]
 [162. ]
 [ 91.4]
 [106.5]
 [135. ]
 [ 90.8]
 [127.5]
 [135. ]
 [ 96.1]
 [113.8]
 [147. ]
 [129.3]
 [135. ]
 [ 86.8]
 [111.5]
 [103.8]
 [103.8]
 [132. ]
 [163. ]
 [129.3]
 [106.5]
 [106.5]
 [124. ]
 [135. ]
 [135. ]
 [106.5]
 [135. ]
 [139. ]
 [163. ]
 [163. ]
 [135. ]]
